# Generated by Django 4.2.3 on 2023-07-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
    ]
