# Generated by Django 4.2.3 on 2023-07-26 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_first_mame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_mame',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
