# Generated by Django 4.2.3 on 2023-07-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentId',
            new_name='student_id',
        ),
    ]
