# Generated by Django 4.1.5 on 2023-07-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_studentid_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registrationNo',
            new_name='registration_num',
        ),
    ]
