# Generated by Django 4.1.5 on 2023-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumManagement', '0004_alter_subject_class_associated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
