# Generated by Django 4.1.5 on 2023-12-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculumManagement', '0007_remove_attendance_id_attendance_attendance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
